In [2]:
setwd('/home/matt/MSOR/ISYE7406/ML-Ex-Rates/Results')
library(class)
library(MASS)
library(pls)
library(lars)
library(lattice)
library(dplyr)

In [3]:
#setwd('/home/matt/MSOR/ISYE7406/ML-Ex-Rates/Data')
#ex_rates <- read.csv('oecd.csv')
#ex_rates <- subset(ex_rates, ex_rates$Country.y == 'canada' |
#                  ex_rates$Country.y == 'europe' |
#                  ex_rates$Country.y == 'mexico' |
#                  ex_rates$Country.y == 'japan' |
#                  ex_rates$Country.y == 'korea')
#setwd('/home/matt/MSOR/ISYE7406/ML-Ex-Rates/Results')
#write.csv(ex_rates, file = 'topfive.csv')

In [95]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

In [103]:
country <- 'europe'
        full <- read.csv(paste(country,'_full.csv',sep=''))
        full <- full[,-1]
        rownames(full) <- 1:nrow(full)

        #AIC Model
        regmodel <- lm(Pct_Chg ~ ., data = full)
        min.model = lm(Pct_Chg ~ 1, data = full)
        max_model <- formula(regmodel)
        linreg_AIC = step(min.model, direction = 'forward',
                 scope = max_model, trace = FALSE)

        vars <- as.character(formula(linreg_AIC))
        var_list <- unlist(strsplit(vars[3],' +'))
        var_list <- var_list[c(TRUE,FALSE)]
        var_list <- c('Pct_Chg',var_list)
        aic_vars <- full[var_list]
head(aic_vars)

Pct_Chg Infl_d  Exchange lag4.Exchange Int_d Int_f X1Y_Yield_d Infl_f
1 -0.12595980    2.7 0.9870694     0.9526531  5.50  3.00    4.830688    1.9
2 -0.12219941    3.2 1.0168802     0.9340557  5.50  3.00    2.187598    1.9
3 -0.11418335    3.8 1.0370217     0.9682417  5.75  3.25    1.200000    1.9
4 -0.11699841    3.1 1.0583130     0.9891197  6.00  3.50    3.131876    1.7
5 -0.14778928    3.2 1.1038746     0.9870694  6.00  3.75    6.186037    1.7
6 -0.08403199    3.7 1.0520779     1.0168802  6.50  3.75    7.800000    2.1
  lag4.X1Y_Yield_d  FER_f    GDPG_f X1Y_Yield_f  BOT_d lag1.X1Y_Yield_d
1         5.100000 256197 -3.475705    1.247301 -27088         7.100000
2         6.467593 254551 -3.303074    1.297188 -29930         4.830688
3         7.474684 256904 -3.770000    1.300000 -31154         2.187598
4         7.100000 252820 -4.851150    1.219803 -28800         1.200000
5         4.830688 252956 -6.148299    1.075570 -29813         3.131876
6         2.187598 253695 -7.170000    0.900000 -30966         6.186037
  lag3.Infl_f lag2.X1Y_Yield_d lag3.X1Y_Yield_f lag1.Exchange lag4.Int_f
1         1.4         7.474684         1.172474     0.9891197        2.5
2         1.5         7.100000         1.187530     0.9870694        2.5
3         1.7         4.830688         1.200000     1.0168802        2.5
4         1.9         2.187598         1.247301     1.0370217        3.0
5         1.9         1.200000         1.297188     1.0583130        3.0
6         1.9         3.131876         1.300000     1.1038746        3.0
  lag4.Int_d lag1.X1Y_Yield_f lag2.X1Y_Yield_f   BOT_f lag4.Infl_f
1       5.25         1.200000         1.187530 -7717.2         1.2
2       5.25         1.247301         1.200000 -2372.5         1.4
3       5.25         1.297188         1.247301  -458.7         1.5
4       5.50         1.300000         1.297188 -2201.3         1.7
5       5.50         1.219803         1.300000 -3422.8         1.9
6       5.50         1.075570         1.219803 -1651.2         1.9

In [111]:
test_lin_models <- function(country, B){
         
        full <- read.csv(paste(country,'_full.csv',sep=''))
        full <- full[,-1]
        rownames(full) <- 1:nrow(full)
    
        #Structural Model
        # struct <- subset(full, select = -c(GDPG_d,GDPG_f,BOT_f,BOT_d,FER_f))
    
        #AIC Model
        regmodel <- lm(Pct_Chg ~ ., data = full)
        min.model = lm(Pct_Chg ~ 1, data = full)
        max_model <- formula(regmodel)
        linreg_AIC = step(min.model, direction = 'forward',
                 scope = max_model, trace = FALSE)
        vars <- as.character(formula(linreg_AIC))
        var_list <- unlist(strsplit(vars[3],' +'))
        var_list <- var_list[c(TRUE,FALSE)]
        var_list <- c('Pct_Chg',var_list)
        aic_vars <- full[var_list]

        # Split into training and testing sets
        n <- dim(full)[1]
        n1 <- round(n/7)
        B <- 100
    
        # Test Full Model

        # Linear Regression -- Full Model
        set.seed(19890211)
        linreg.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)            
            train <- aic_vars[-flag,]; test <- aic_vars[flag,]
    
            regmodel <- lm(Pct_Chg ~ ., data = train)
            linreg.test <- predict.lm(regmodel,test[,-1])
            linreg.TE <- mean( (test[,1]-linreg.test)^2)
            linreg.TE_list <- c(linreg.TE_list, linreg.TE)
    
        }    
    
        # Ridge Regression -- Full Model
        set.seed(19890211)
        ridge.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)            
            train <- aic_vars[-flag,]; test <- aic_vars[flag,]
    
            ridgereg <- lm.ridge(Pct_Chg ~ ., data = train, 
                        lambda = seq(0,10,0.001))
            lambdaopt <- which.min(ridgereg$GCV)
            ridge_coef <- coef(ridgereg)[lambdaopt,]
            ridge_testmat <- as.matrix(cbind(1,test[,-1]))
            ridge.test <- as.matrix(ridge_testmat %*% ridge_coef)
            ridge.TE <- mean( (test[,1] - ridge.test)^2)
            ridge.TE_list <- c(ridge.TE_list, ridge.TE)
    
        }
    
        # Lasso Regression -- Full Model
        set.seed(19890211)
        lasso.TE_list <- vector(length=0)
        lasso_lambda <- 0
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)    
            train <- aic_vars[-flag,]; test <- aic_vars[flag,]
    
            lassoreg <- lars( x= as.matrix(train[,-1]),
                            y = train[,1], type = 'lasso')
            Cp1 <- summary(lassoreg)$Cp
            index1 <- which.min(Cp1)
            lasso_coef <- coef(lassoreg)[index1,]
            if (is.na(lassoreg$lambda[index1])==FALSE){
                lasso_lambda <- lassoreg$lambda[index1]
            }
            lassoreg.fit <- predict(lassoreg, as.matrix(test[,-1]),
                                   s = lasso_lambda, type = 'fit',
                                   mode = 'lambda')
            lassoreg.test <- lassoreg.fit$fit
            lassoreg.TE <- mean( (test[,1]-lassoreg.test)^2)
            lasso.TE_list <- c(lasso.TE_list, lassoreg.TE)
                
        }
    
        # PCR -- Full Model
        set.seed(19890211)
        pcreg.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)
            train <- aic_vars[-flag,]; test <- aic_vars[flag,]
            
            pcreg <- pcr(Pct_Chg ~ ., data = train,
                        validation = 'CV')
            comps <- dim(train)[2]-1
            pcreg.test <- predict(pcreg, ncomp = comps,
                                 newdata = test[,-1])
            pcreg.TE <- mean((test[,1]-pcreg.test)^2)
            pcreg.TE_list <- c(pcreg.TE_list, pcreg.TE)
        }
    
        # Test Structural Model
"
        # Linear Regression -- Structural Model
        set.seed(19890211)
        linreg2.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)
            train <- struct[-flag,]; test <- struct[flag,]
    
            regmodel <- lm(Pct_Chg ~ ., data = train)
            linreg.test <- predict.lm(regmodel,test[,-1])
            linreg.TE <- mean( (test[,1]-linreg.test)^2)
            linreg2.TE_list <- c(linreg2.TE_list, linreg.TE)
    
        }    
    
        # Ridge Regression -- Structural Model
        set.seed(19890211)
        ridge2.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)
            train <- struct[-flag,]; test <- struct[flag,]
    
            ridgereg <- lm.ridge(Pct_Chg ~ ., data = train, 
                        lambda = seq(0,10,0.001))
            lambdaopt <- which.min(ridgereg$GCV)
            ridge_coef <- coef(ridgereg)[lambdaopt,]
            ridge_testmat <- as.matrix(cbind(1,test[,-1]))
            ridge.test <- as.matrix(ridge_testmat %*% ridge_coef)
            ridge.TE <- mean( (test[,1] - ridge.test)^2)
            ridge2.TE_list <- c(ridge2.TE_list, ridge.TE)
    
        }
    
        # Lasso Regression -- Structural Model
        set.seed(19890211)
        lasso2.TE_list <- vector(length=0)
        lasso_lambda <- 0
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)
            train <- struct[-flag,]; test <- struct[flag,]
    
            lassoreg <- lars( x= as.matrix(train[,-1]),
                            y = train[,1], type = 'lasso')
            Cp1 <- summary(lassoreg)$Cp
            index1 <- which.min(Cp1)
            lasso_coef <- coef(lassoreg)[index1,]
            if (is.na(lassoreg$lambda[index1])==FALSE){
                lasso_lambda <- lassoreg$lambda[index1]
            }
            lassoreg.fit <- predict(lassoreg, as.matrix(test[,-1]),
                                   s = lasso_lambda, type = 'fit',
                                   mode = 'lambda')
            lassoreg.test <- lassoreg.fit$fit
            lassoreg.TE <- mean( (test[,1]-lassoreg.test)^2)
            lasso2.TE_list <- c(lasso2.TE_list, lassoreg.TE)
                
        }
    
        # PCR -- Structural Model
        set.seed(19890211)
        pcreg2.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)
            train <- struct[-flag,]; test <- struct[flag,]
            
            pcreg <- pcr(Pct_Chg ~ ., data = train,
                        validation = 'CV')
            comps <- dim(train)[2]-1
            pcreg.test <- predict(pcreg, ncomp = comps,
                                 newdata = test[,-1])
            pcreg.TE <- mean((test[,1]-pcreg.test)^2)
            pcreg2.TE_list <- c(pcreg2.TE_list, pcreg.TE)
        }"
    
        # Naive
        set.seed(19890211)
        naive.TE_list <- vector(length=0)
        for(i in 1:B){
            start <- sample(1:(n-n1-1),1)
            flag <- (start):(start+n1)
            train <- full[-flag,]; test <- full[flag,]
            naive.TE <- mean ( (test[,1])^2)
            naive.TE_list <- c(naive.TE_list,naive.TE)
        }
    
        output1 <- c('Full','Linear','Ridge',
                    'Lasso', 'PCR','Naive')
        output1 <- rbind(output1, c('Mean', mean(linreg.TE_list),
                             mean(ridge.TE_list),mean(lasso.TE_list),
                             mean(pcreg.TE_list), mean(naive.TE_list)))
        output1 <- rbind(output1, c('Variance', var(linreg.TE_list),
                             var(ridge.TE_list), var(lasso.TE_list),
                             var(pcreg.TE_list),var(naive.TE_list)))
        output1 <- rbind(output1, c('t-test',
                t.test(linreg.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value,
                t.test(ridge.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value,
                t.test(lasso.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value,
                t.test(pcreg.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value, NA))
    "
        output2 <- c('Struct','Linear','Ridge',
                     'Lasso','PCR','Naive')
        output2 <- rbind(output2, c('Mean', mean(linreg2.TE_list),
                             mean(ridge2.TE_list),mean(lasso2.TE_list),
                              mean(pcreg2.TE_list), mean(naive.TE_list)))
        output2 <- rbind(output2, c('Variance', var(linreg2.TE_list),
                             var(ridge2.TE_list), var(lasso2.TE_list),
                              var(pcreg2.TE_list),var(naive.TE_list)))
        output2 <- rbind(output2, c('t-test',
                t.test(linreg2.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value,
                t.test(ridge2.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value,
                t.test(lasso2.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value,
                t.test(pcreg2.TE_list,naive.TE_list,alternative='less',paired=TRUE)$p.value, NA))        
        output <- rbind(output1,output2)"
        return(output1)
}

In [113]:
print('canada')
test_lin_models('canada',100)
print('europe')
test_lin_models('europe',100)
print('mexico')
test_lin_models('mexico',100)
print('japan')
test_lin_models('japan',100)
print('korea')
test_lin_models('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Linear"               "Ridge"               
        "Mean"     "0.00159875874902802"  "0.00163495911601735" 
        "Variance" "1.8076106518812e-06"  "2.18115664245511e-06"
        "t-test"   "1.02589982740522e-13" "5.87899156262592e-14"
        [,4]                   [,5]                   [,6]                  
output1 "Lasso"                "PCR"                  "Naive"               
        "0.00167055253017585"  "0.00168030294823137"  "0.0062549840677834"  
        "2.27529563451075e-06" "3.28226239497463e-06" "4.08759630901676e-05"
        "6.04501958764423e-14" "3.23635951248714e-10" NA

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Linear"               "Ridge"               
        "Mean"     "0.016618198784156"    "0.0168966500362877"  
        "Variance" "0.000344699153596589" "0.000363242424727663"
        "t-test"   "0.997696261742745"    "0.99816553240154"    
        [,4]                   [,5]                   [,6]                  
output1 "Lasso"                "PCR"                  "Naive"               
        "0.0176556842221414"   "0.0154978255233342"   "0.011111184479792"   
        "0.000422783354448573" "0.000328094004117997" "4.05408485389392e-05"
        "0.99895886488831"     "0.986582278249383"    NA

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Linear"               "Ridge"               
        "Mean"     "0.0036748269489863"   "0.00401060216098086" 
        "Variance" "1.35193254285862e-05" "2.23012826896396e-05"
        "t-test"   "2.61165566367476e-14" "1.42073470330894e-14"
        [,4]                   [,5]                   [,6]                  
output1 "Lasso"                "PCR"                  "Naive"               
        "0.00367401762093596"  "0.00356926135602814"  "0.0102966992015578"  
        "1.34528988366173e-05" "1.18436613109807e-05" "0.000106577420324928"
        "7.35436352560851e-15" "2.50249546748883e-08" NA

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Linear"               "Ridge"               
        "Mean"     "0.0325397876991029"   "0.0330245244797765"  
        "Variance" "0.000676847881466286" "0.000665741018306433"
        "t-test"   "0.999983024972442"    "0.999992621700252"   
        [,4]                   [,5]                   [,6]                  
output1 "Lasso"                "PCR"                  "Naive"               
        "0.0303405861010078"   "0.0348893910292499"   "0.019877313248319"   
        "0.000504014119173177" "0.000765619797189318" "0.000150964183618519"
        "0.99995232514619"     "0.999996631802528"    NA

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Linear"               "Ridge"               
        "Mean"     "0.00573998668310545"  "0.00561880857514345" 
        "Variance" "2.66977510337126e-05" "2.56695864230436e-05"
        "t-test"   "1.74966388843721e-11" "1.04433398913159e-11"
        [,4]                   [,5]                   [,6]                  
output1 "Lasso"                "PCR"                  "Naive"               
        "0.00556800994543908"  "0.00642317496479371"  "0.0114809536417125"  
        "2.38882847945754e-05" "3.02544775910044e-05" "0.000125398686492762"
        "9.65570126992297e-12" "2.56971958497158e-05" NA