In [2]:
setwd('C:/Users/Eddie/Documents/GitHub/ML-Ex-Rates/Results')
library(rpart)
library(randomForest)
library(dplyr)

test_full_trees <- function(country, B){
    full <- read.csv(paste(country,'_full.csv',sep=''))
    full <- full[,-1]
    rownames(full) <- 1:nrow(full)
    
    # Split into testing and training
    n <- dim(full)[1]
    n1 <- round(n/5)
    
    # full Tree Models
    set.seed(19890211)
    fulltree.TE_list <- vector(length=0)
    for(i in 1:B){
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        fulltree.test <- predict(treemodel,test[,-1])
        fulltree.TE <- mean((test[,1]-fulltree.test)^2)
        fulltree.TE_list <- c(fulltree.TE_list, fulltree.TE)
    }
    
    # pruned tree models
    set.seed(19890211)
    fullpruned.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        prunedtree <- prune(treemodel,
                    treemodel$cptable[which.min(treemodel$cptable[,'xerror']),"CP"])
        fullpruned.test <- predict(prunedtree,test[,-1])
        fullpruned.TE <- mean((test[,1]-fullpruned.test)^2)
        fullpruned.TE_list <- c(fullpruned.TE_list,fullpruned.TE)  
    }
    
    # Full Random Forest
    set.seed(19890211)
    fullforest.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        forestmodel <- randomForest(Pct_Chg ~ ., data = train)
        fullforest.test <- predict(forestmodel,test[,-1])
        fullforest.TE <- mean((test[,1]-fullforest.test)^2)
        fullforest.TE_list <- c(fullforest.TE_list, fullforest.TE) 
        
    }

output1 <- c('Full','Full Tree','Full Pruned', 'Full Forest')
output1 <- rbind(output1,c('Mean',mean(fulltree.TE_list),mean(fullpruned.TE_list),mean(fullforest.TE_list)))
output1 <- rbind(output1,c('Variance',var(fulltree.TE_list),var(fullpruned.TE_list),var(fullforest.TE_list)))


return(output1)

}

print('canada')
test_full_trees('canada',10)
print('europe')
test_full_trees('europe',10)
print('mexico')
test_full_trees('mexico',10)
print('japan')
test_full_trees('japan',10)
print('korea')
test_full_trees('korea',10)

randomForest 4.6-10
Type rfNews() to see new features/changes/bug fixes.

Attaching package: 'dplyr'

The following object is masked from 'package:randomForest':

    combine

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00286186754928327"  "0.00272616818424158" 
        "Variance" "9.73573559258191e-06" "1.00597794608522e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00371842861805248" 
        "2.89904602671658e-05"

[1] "europe"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0141188413996312"   "0.0145516771244521" 
        "Variance" "2.14367588826176e-05" "3.0844576614562e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00887244130575673" 
        "2.27384581385476e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0077701432084026"   "0.00762001524070815" 
        "Variance" "6.87165671409264e-05" "7.24558380221787e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00513111309502257" 
        "2.51513461688025e-05"

[1] "japan"


[,1]       [,2]                  [,3]                  
output1 "Full"     "Full Tree"           "Full Pruned"         
        "Mean"     "0.030954847425092"   "0.0320798515009658"  
        "Variance" "0.00015674290687077" "0.000166866566216661"
        [,4]                  
output1 "Full Forest"         
        "0.0172915545739086"  
        "5.54138475996108e-05"

[1] "korea"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0107077822435343"   "0.0104522252175932" 
        "Variance" "8.12971069771746e-05" "8.1545096726855e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0115367621337741"  
        "0.000113930868570151"

In [3]:
test_aic_trees <- function(country, B){    
    full <- read.csv(paste(country,'_full.csv',sep=''))
    full <- full[,-1]
    rownames(full) <- 1:nrow(full)

    #AIC Model
    regmodel <- lm(Pct_Chg ~ ., data = full)
    min.model = lm(Pct_Chg ~ 1, data = full)
    max_model <- formula(regmodel)
    linreg_AIC = step(min.model, direction = 'forward',
             scope = max_model, trace = FALSE)
    vars <- as.character(formula(linreg_AIC))
    var_list <- unlist(strsplit(vars[3],' +'))
    var_list <- var_list[c(TRUE,FALSE)]
    var_list <- c('Pct_Chg',var_list)
    aic_vars <- full[var_list]

    # Split into testing and training
    n <- dim(full)[1]
    n1 <- round(n/5)

    # AIC Tree Models
    set.seed(19890211)
    AICtree.TE_list <- vector(length=0)
    for(i in 1:B){
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- aic_vars[-flag,]
        test <- aic_vars[flag,]

        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        AICtree.test <- predict(treemodel,test[,-1])
        AICtree.TE <- mean((test[,1]-AICtree.test)^2)
        AICtree.TE_list <- c(AICtree.TE_list, AICtree.TE)
    }

    # AIC pruned tree models
    set.seed(19890211)
    AICpruned.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- aic_vars[-flag,]
        test <- aic_vars[flag,]

        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        prunedtree <- prune(treemodel,
                    treemodel$cptable[which.min(treemodel$cptable[,'xerror']),"CP"])
        AICpruned.test <- predict(prunedtree,test[,-1])
        AICpruned.TE <- mean((test[,1]-AICpruned.test)^2)
        AICpruned.TE_list <- c(AICpruned.TE_list,AICpruned.TE)  
    }

    # AIC Random Forest
    set.seed(19890211)
    AICforest.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- aic_vars[-flag,]
        test <- aic_vars[flag,]

        forestmodel <- randomForest(Pct_Chg ~ ., data = train)
        AICforest.test <- predict(forestmodel,test[,-1])
        AICforest.TE <- mean((test[,1]-AICforest.test)^2)
        AICforest.TE_list <- c(AICforest.TE_list, AICforest.TE) 

    }

    output1 <- c('AIC','AIC Tree','AIC Pruned', 'AIC Forest')
    output1 <- rbind(output1,c('Mean',mean(AICtree.TE_list),mean(AICpruned.TE_list),mean(AICforest.TE_list)))
    output1 <- rbind(output1,c('Variance',var(AICtree.TE_list),var(AICpruned.TE_list),var(AICforest.TE_list)))


    return(output1)
}


print('canada')
test_aic_trees('canada',10)
print('europe')
test_aic_trees('europe',10)
print('mexico')
test_aic_trees('mexico',10)
print('japan')
test_aic_trees('japan',10)
print('korea')
test_aic_trees('korea',10)

[1] "canada"


ERROR: Error in `[.data.frame`(full, var_list): undefined columns selected


[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0103816242516105"   "0.0104506346548643"  
        "Variance" "1.99709815212007e-05" "1.91521608093144e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.0124021010473583"  
        "5.31634209224944e-05"

[1] "mexico"


ERROR: Error in `[.data.frame`(full, var_list): undefined columns selected


[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0241485786400307"   "0.0242219651472977"  
        "Variance" "5.39216891991406e-05" "5.15751108636021e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.0190773710410276"  
        "7.23097547629656e-05"

[1] "korea"


[,1]       [,2]                   [,3]                 
output1 "AIC"      "AIC Tree"             "AIC Pruned"         
        "Mean"     "0.00942921702920031"  "0.00949326438061241"
        "Variance" "0.000125754514990017" "0.000125489555476"  
        [,4]                  
output1 "AIC Forest"          
        "0.00720811238193397" 
        "3.11268213505039e-05"

In [5]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))


full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                  [,3]                  
output1 "Full"     "Full Tree"           "Full Pruned"         
        "Mean"     "0.00641176429333256" "0.0065465547044811"  
        "Variance" "5.5251285524091e-05" "5.63924147604228e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00592102732259112" 
        "5.15281046833127e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.021517387729752"    "0.0215261055995086"  
        "Variance" "0.000195337155232761" "0.000181170412091388"
        [,4]                 
output1 "Full Forest"        
        "0.0129708191130335" 
        "6.2762800379708e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00594388731394514"  "0.00578707303641143" 
        "Variance" "1.64723089097214e-05" "1.40823681559213e-05"
        [,4]                 
output1 "Full Forest"        
        "0.00448069327809074"
        "2.2505511379684e-05"

[1] "japan"


[,1]       [,2]                  [,3]                  
output1 "Full"     "Full Tree"           "Full Pruned"         
        "Mean"     "0.0305771028683636"  "0.0303814468799378"  
        "Variance" "0.00020026253504266" "0.000202354448876688"
        [,4]                 
output1 "Full Forest"        
        "0.0246513838794793" 
        "0.00011347981810077"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.014704428732304"    "0.0146992590139343"  
        "Variance" "9.26038752054188e-05" "9.21961307124316e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00948329971078278" 
        "0.000108471980005754"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00558007925988568"  "0.00558007925988568" 
        "Variance" "3.71903116462581e-05" "3.71903116462581e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00746676649782603" 
        "8.15469707084641e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.019706882114691"    "0.0195392897289164"  
        "Variance" "0.000217553725585682" "0.000199982784910124"
        [,4]                  
output1 "AIC Forest"          
        "0.0120787954531309"  
        "5.09501979621594e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00566359308998456"  "0.0055931082863976"  
        "Variance" "1.72954007532264e-05" "1.67116080415411e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00345560664662473" 
        "9.31812349670489e-06"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.033376280576257"    "0.0332824737418788"  
        "Variance" "0.000252324471835863" "0.000252883012459207"
        [,4]                  
output1 "AIC Forest"          
        "0.0236266491650808"  
        "9.71862810487227e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0145229900137072"   "0.0145205879900288"  
        "Variance" "9.50705703903392e-05" "9.45136995809354e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00856645783845349" 
        "9.42903210880554e-05"

In [6]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}
print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00667886751046769"  "0.00667092755628869" 
        "Variance" "5.37516344168912e-05" "5.34013552251048e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00593793699290156" 
        "5.00421390854491e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0206253139444022"   "0.0205606951851182"  
        "Variance" "0.000167544939892893" "0.000168455265277135"
        [,4]                  
output1 "Full Forest"         
        "0.0136384271967105"  
        "6.14278105108876e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00625607363553695"  "0.00598287275360591" 
        "Variance" "2.14519839409811e-05" "2.04786173204559e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00386712816203982" 
        "1.39153567291263e-05"

[1] "japan"


[,1]       [,2]                 [,3]                  
output1 "Full"     "Full Tree"          "Full Pruned"         
        "Mean"     "0.0343235037139852" "0.0343602614650828"  
        "Variance" "0.0003816387840824" "0.000381806460137255"
        [,4]                  
output1 "Full Forest"         
        "0.0216769548587381"  
        "8.62770507001568e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0146362499094438"   "0.0146186166833097"  
        "Variance" "0.000100375631619332" "0.000100027511711266"
        [,4]                  
output1 "Full Forest"         
        "0.00942774477563622" 
        "0.000100749326458237"

[1] "canada"


[,1]       [,2]                   [,3]                 
output1 "AIC"      "AIC Tree"             "AIC Pruned"         
        "Mean"     "0.00664331220730208"  "0.00663195759815923"
        "Variance" "5.39191653016944e-05" "5.3305149280659e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00507227640354868" 
        "4.44650877259637e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0208650001374509"   "0.0206313947090019"  
        "Variance" "0.000209639656237631" "0.000191729305167676"
        [,4]                  
output1 "AIC Forest"          
        "0.0130267407368825"  
        "7.35594820544872e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00560876917290206"  "0.00550172304608404" 
        "Variance" "2.37480506055359e-05" "2.18911356610622e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00460318416430582" 
        "2.92508824097789e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0375041033727014"   "0.0375621867049354"  
        "Variance" "0.000410730763302962" "0.000424241350685863"
        [,4]                  
output1 "AIC Forest"          
        "0.0241980286282959"  
        "0.000110603114136601"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.014100728593341"    "0.0140096080130799"  
        "Variance" "9.96637363364853e-05" "9.99473524602808e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00718709750764093" 
        "6.76180906516778e-05"

In [8]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00633638793798527"  "0.00621977331115025" 
        "Variance" "4.82808774944263e-05" "4.58837573632282e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0048794289887415"  
        "3.45100540877489e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.019414823008102"    "0.0198637424860631"  
        "Variance" "0.000124531053160331" "0.000146740880463341"
        [,4]                  
output1 "Full Forest"         
        "0.0149496372429318"  
        "7.91779814850825e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00712951067124779"  "0.006349107171787"   
        "Variance" "2.37397959290659e-05" "2.20091365078166e-05"
        [,4]                 
output1 "Full Forest"        
        "0.00436222548438125"
        "2.2875298620295e-05"

[1] "japan"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0360778736893072"   "0.0359610195626952" 
        "Variance" "0.000486223230468644" "0.00048827644266565"
        [,4]                  
output1 "Full Forest"         
        "0.0248570789558837"  
        "0.000135948374188767"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0150554397299359"   "0.0150853211236856"  
        "Variance" "0.000109444547275131" "0.000108182539887836"
        [,4]                  
output1 "Full Forest"         
        "0.00740004299870666" 
        "6.29569252341419e-05"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00627294312953143"  "0.00619556303082002" 
        "Variance" "4.80517780049542e-05" "4.68043332163592e-05"
        [,4]                 
output1 "AIC Forest"         
        "0.00481028323234883"
        "3.5674254033493e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0190970975642422"   "0.019213022448037"   
        "Variance" "0.000163870672136133" "0.000165106260703694"
        [,4]                  
output1 "AIC Forest"          
        "0.0126717117906078"  
        "5.52181486589707e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00675584774646629"  "0.00648876151961417" 
        "Variance" "2.23212403385359e-05" "2.15503427442339e-05"
        [,4]                 
output1 "AIC Forest"         
        "0.00566365139596594"
        "3.2637064296227e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0352526249919635"   "0.0353772815439313"  
        "Variance" "0.000330508942764121" "0.000333081431385631"
        [,4]                  
output1 "AIC Forest"          
        "0.0241965965505857"  
        "0.000123719964564766"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0158511860221116"   "0.0158024127430073"  
        "Variance" "0.000102645035548097" "0.000104306862244824"
        [,4]                  
output1 "AIC Forest"          
        "0.00879375733892992" 
        "7.89547067188721e-05"

In [9]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00680462829068305"  "0.00687922575313016" 
        "Variance" "6.60472535202397e-05" "6.65188037837501e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00457214475174723" 
        "3.24506608638021e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0227619834671656"   "0.0227924600210191"  
        "Variance" "0.000186138166449033" "0.000193379926449185"
        [,4]                  
output1 "Full Forest"         
        "0.0150212541682689"  
        "8.59728851011119e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00761529767218638"  "0.00725202038449497" 
        "Variance" "2.15930172441032e-05" "2.35584006223383e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0042362671970574"  
        "2.29807437420018e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0271469183726131"   "0.0269859583786277"  
        "Variance" "0.000176186426366962" "0.000173958237659692"
        [,4]                  
output1 "Full Forest"         
        "0.0201187979343201"  
        "7.69943473833957e-05"

[1] "korea"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0126474961024147"   "0.0126839409103701" 
        "Variance" "9.35597789380846e-05" "9.3474211977837e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00884049736995193" 
        "8.61131221564454e-05"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00755913569992696"  "0.00745220423134806" 
        "Variance" "7.28569846419308e-05" "7.12065290814968e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00562451767012285" 
        "5.15259520479532e-05"

[1] "europe"


[,1]       [,2]                  [,3]                 
output1 "AIC"      "AIC Tree"            "AIC Pruned"         
        "Mean"     "0.0231580337235506"  "0.023220248191459"  
        "Variance" "0.00016882199437296" "0.00018131805611903"
        [,4]                  
output1 "AIC Forest"          
        "0.014707216356122"   
        "0.000110588585228883"

[1] "mexico"


[,1]       [,2]                   [,3]                 
output1 "AIC"      "AIC Tree"             "AIC Pruned"         
        "Mean"     "0.0070837145777984"   "0.00691456032435144"
        "Variance" "2.70034712708398e-05" "2.7028240692858e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.0057785952347072"  
        "4.36514469579504e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0330721868624739"   "0.0330195971992459"  
        "Variance" "0.000288205113671281" "0.000291853003529252"
        [,4]                 
output1 "AIC Forest"         
        "0.0218985084393031" 
        "7.9319272208785e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0119839174585882"   "0.0119757402523155"  
        "Variance" "9.64884973850864e-05" "9.75991560001485e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00879097966967551" 
        "9.46950699156657e-05"

In [10]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00738881355527953"  "0.00734461551975625" 
        "Variance" "6.81083472834278e-05" "6.63864784116058e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00449553836717566" 
        "3.53430112402808e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0217281710690849"   "0.0219035232598653"  
        "Variance" "0.000180664463967327" "0.000183393530030901"
        [,4]                 
output1 "Full Forest"        
        "0.0143217478868706" 
        "9.1887159221236e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.00724846677029357"  "0.00649524257280933"
        "Variance" "1.85498731793957e-05" "1.9584667071375e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00424786699461888" 
        "1.93397474779781e-05"

[1] "japan"


[,1]       [,2]                 [,3]                  
output1 "Full"     "Full Tree"          "Full Pruned"         
        "Mean"     "0.0253874887534733" "0.0251580667934505"  
        "Variance" "9.236890946203e-05" "8.74002079456116e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0215440043172009"  
        "8.24614362369181e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0135187054057505"   "0.0134902313402889"  
        "Variance" "8.35552373586643e-05" "7.99134918145662e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00937630844053643" 
        "9.80410019722864e-05"

[1] "canada"


[,1]       [,2]                   [,3]                 
output1 "AIC"      "AIC Tree"             "AIC Pruned"         
        "Mean"     "0.00936332206653394"  "0.00938342187183933"
        "Variance" "9.02021315849426e-05" "9.0278076750857e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00481623399955967" 
        "4.43161330544487e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0210894373726745"   "0.0215459129153275"  
        "Variance" "0.000230576320500969" "0.000234626999993755"
        [,4]                  
output1 "AIC Forest"          
        "0.0144243483409743"  
        "9.28710038685665e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00639137793224928"  "0.00602320275556258" 
        "Variance" "1.65223040486217e-05" "1.62217860976515e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00404840897692636" 
        "1.07588451486262e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.026292644842399"    "0.0260870577934918"  
        "Variance" "0.000104323242956075" "0.000102268321690948"
        [,4]                  
output1 "AIC Forest"          
        "0.0202909203876781"  
        "6.90613100201775e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.012729679550198"    "0.0128071321914963"  
        "Variance" "7.43913582202799e-05" "7.38776897245598e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00966755904843823" 
        "0.000111925098700196"

In [11]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4)) %>%
    
                mutate(lag5.Exchange = lag(Exchange,5)) %>%
                mutate(lag5.X1Y_Yield_d = lag(X1Y_Yield_d,5)) %>%
                mutate(lag5.X1Y_Yield_f = lag(X1Y_Yield_f,5)) %>%
                mutate(lag5.Infl_d = lag(Infl_d,5)) %>%
                mutate(lag5.Infl_f = lag(Infl_f,5)) %>%
                mutate(lag5.Int_d = lag(Int_d,5)) %>%
                mutate(lag5.Int_f = lag(Int_f,5))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00632818371050797"  "0.00633556804805361" 
        "Variance" "5.11763283085318e-05" "5.07342179348371e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00572198516599678" 
        "6.15439822029388e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0234175207719483"   "0.0233819695564869"  
        "Variance" "0.000270758611027842" "0.000266204535785848"
        [,4]                  
output1 "Full Forest"         
        "0.0157595637793029"  
        "0.000111320044988505"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00707414274690525"  "0.00706475831543387" 
        "Variance" "3.20399959092261e-05" "3.13438412036878e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00376004145962435" 
        "1.19293745642211e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0251392531462186"   "0.0249481180410519"  
        "Variance" "0.000103436367957419" "0.000102604706767962"
        [,4]                  
output1 "Full Forest"         
        "0.0194840474349247"  
        "7.65668672750947e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0155901105752191"   "0.0154263002935465"  
        "Variance" "8.14713952433877e-05" "8.37404049007351e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00969578948302358" 
        "9.62410538415353e-05"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00521094181817907"  "0.00522078120270162" 
        "Variance" "5.08841202604072e-05" "5.10587105166066e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00431271251551261" 
        "3.64348644555315e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0215349924348071"   "0.0219746015227531"  
        "Variance" "0.000303058455293629" "0.000307268455685622"
        [,4]                  
output1 "AIC Forest"          
        "0.0148148195962615"  
        "8.94192690853607e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00620051397700545"  "0.00621235669664418" 
        "Variance" "2.82760239485212e-05" "2.95301316308539e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00313367347085067" 
        "6.37894489359502e-06"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0271566346099998"   "0.0269836296865464"  
        "Variance" "0.000107655433766088" "0.000102997027021231"
        [,4]                  
output1 "AIC Forest"          
        "0.0206899863938671"  
        "6.59539813342089e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0142880214202198"   "0.0143698389666439"  
        "Variance" "8.82222133241143e-05" "8.62851260314784e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.009413044993738"   
        "0.000108119653996643"

In [12]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4)) %>%
    
                mutate(lag5.Exchange = lag(Exchange,5)) %>%
                mutate(lag5.X1Y_Yield_d = lag(X1Y_Yield_d,5)) %>%
                mutate(lag5.X1Y_Yield_f = lag(X1Y_Yield_f,5)) %>%
                mutate(lag5.Infl_d = lag(Infl_d,5)) %>%
                mutate(lag5.Infl_f = lag(Infl_f,5)) %>%
                mutate(lag5.Int_d = lag(Int_d,5)) %>%
                mutate(lag5.Int_f = lag(Int_f,5)) %>%
    
                mutate(lag6.Exchange = lag(Exchange,6)) %>%
                mutate(lag6.X1Y_Yield_d = lag(X1Y_Yield_d,6)) %>%
                mutate(lag6.X1Y_Yield_f = lag(X1Y_Yield_f,6)) %>%
                mutate(lag6.Infl_d = lag(Infl_d,6)) %>%
                mutate(lag6.Infl_f = lag(Infl_f,6)) %>%
                mutate(lag6.Int_d = lag(Int_d,6)) %>%
                mutate(lag6.Int_f = lag(Int_f,6))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0071538424936152"   "0.00717573546335076" 
        "Variance" "8.53476302772296e-05" "8.62813892814601e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0052191942049831"  
        "5.61641551625972e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0197017431857603"   "0.0200090359426321"  
        "Variance" "7.48057072340353e-05" "8.17324355308687e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0138535853907209"  
        "8.04226905762999e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00716805401445601"  "0.00703405382511897" 
        "Variance" "3.44142680174562e-05" "3.56502244681072e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00424302502575267" 
        "2.12938058988651e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0245286494969599"   "0.0243260350321499"  
        "Variance" "0.000193136866135706" "0.000189644422648814"
        [,4]                  
output1 "Full Forest"         
        "0.0193611711127937"  
        "6.93531503714816e-05"

[1] "korea"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.014802692344686"    "0.0145284526460965" 
        "Variance" "7.72964409464497e-05" "8.0338864914272e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00942913021717155" 
        "9.17537858274044e-05"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00708421707659448"  "0.00707098616610663" 
        "Variance" "8.66482305722037e-05" "8.25901689452565e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00521801041651024" 
        "5.70695724057031e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0179804588492135"   "0.0179277853712602"  
        "Variance" "9.39203017964397e-05" "9.38430521569059e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.0151018310002651"  
        "8.68009689743722e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                 
output1 "AIC"      "AIC Tree"             "AIC Pruned"         
        "Mean"     "0.00646410551679496"  "0.00636401477026538"
        "Variance" "2.61671551688303e-05" "2.7565087369239e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00408503571876879" 
        "1.66200541745753e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0286944341041191"   "0.0284888042286558"  
        "Variance" "0.000298914275070719" "0.000298721717368116"
        [,4]                  
output1 "AIC Forest"          
        "0.0213237366978958"  
        "6.17467837586999e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0127518374340552"   "0.012817220658813"   
        "Variance" "9.07184186363705e-05" "9.02170593619813e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00933978269579364" 
        "0.000115939827889348"

In [13]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4)) %>%
    
                mutate(lag5.Exchange = lag(Exchange,5)) %>%
                mutate(lag5.X1Y_Yield_d = lag(X1Y_Yield_d,5)) %>%
                mutate(lag5.X1Y_Yield_f = lag(X1Y_Yield_f,5)) %>%
                mutate(lag5.Infl_d = lag(Infl_d,5)) %>%
                mutate(lag5.Infl_f = lag(Infl_f,5)) %>%
                mutate(lag5.Int_d = lag(Int_d,5)) %>%
                mutate(lag5.Int_f = lag(Int_f,5)) %>%
    
                mutate(lag6.Exchange = lag(Exchange,6)) %>%
                mutate(lag6.X1Y_Yield_d = lag(X1Y_Yield_d,6)) %>%
                mutate(lag6.X1Y_Yield_f = lag(X1Y_Yield_f,6)) %>%
                mutate(lag6.Infl_d = lag(Infl_d,6)) %>%
                mutate(lag6.Infl_f = lag(Infl_f,6)) %>%
                mutate(lag6.Int_d = lag(Int_d,6)) %>%
                mutate(lag6.Int_f = lag(Int_f,6)) %>%

                mutate(lag7.Exchange = lag(Exchange,7)) %>%
                mutate(lag7.X1Y_Yield_d = lag(X1Y_Yield_d,7)) %>%
                mutate(lag7.X1Y_Yield_f = lag(X1Y_Yield_f,7)) %>%
                mutate(lag7.Infl_d = lag(Infl_d,7)) %>%
                mutate(lag7.Infl_f = lag(Infl_f,7)) %>%
                mutate(lag7.Int_d = lag(Int_d,7)) %>%
                mutate(lag7.Int_f = lag(Int_f,7))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00554410732563508"  "0.00548976639830343" 
        "Variance" "3.86600009386317e-05" "3.92117883312043e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00522782391276848" 
        "6.26140253121961e-05"

[1] "europe"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0180673327445436"   "0.0183763931652427" 
        "Variance" "8.58200123166978e-05" "9.0641715187494e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0131285449600935"  
        "8.07190210296585e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00721325768698996"  "0.00725397475072899" 
        "Variance" "5.37292688786806e-05" "5.55264993418707e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00448237969565795" 
        "2.12337870789854e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0254430642506339"   "0.0254043683318543"  
        "Variance" "0.000129657793779139" "0.000129830032653653"
        [,4]                  
output1 "Full Forest"         
        "0.0210822317375178"  
        "7.48222616543815e-05"

[1] "korea"


[,1]       [,2]                   [,3]                
output1 "Full"     "Full Tree"            "Full Pruned"       
        "Mean"     "0.0169917663134616"   "0.0168279035731189"
        "Variance" "7.59377551084435e-05" "7.680215998444e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00921727722670517" 
        "7.61292175802515e-05"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00565770208808198"  "0.00572524834733494" 
        "Variance" "3.56651374416174e-05" "3.67834153285657e-05"
        [,4]                 
output1 "AIC Forest"         
        "0.00470689567978302"
        "5.2324891331611e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0184915816718747"   "0.018517733547698"   
        "Variance" "0.000123791397339983" "0.000124281079689817"
        [,4]                  
output1 "AIC Forest"          
        "0.0129722745025327"  
        "4.65945357232759e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                 
output1 "AIC"      "AIC Tree"             "AIC Pruned"         
        "Mean"     "0.00655824984924581"  "0.00660429565925371"
        "Variance" "5.06912283698866e-05" "5.0841478397267e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00404790159244874" 
        "1.39003728685671e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0273959655431472"   "0.0274043770667193"  
        "Variance" "0.000189102781631345" "0.000188695248355497"
        [,4]                 
output1 "AIC Forest"         
        "0.0207074672264812" 
        "6.8523212565192e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0145341481344421"   "0.0148013983457763"  
        "Variance" "8.39074058922083e-05" "8.75664823320566e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.0096775904213935"  
        "0.000113683817060146"

In [14]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4)) %>%
    
                mutate(lag5.Exchange = lag(Exchange,5)) %>%
                mutate(lag5.X1Y_Yield_d = lag(X1Y_Yield_d,5)) %>%
                mutate(lag5.X1Y_Yield_f = lag(X1Y_Yield_f,5)) %>%
                mutate(lag5.Infl_d = lag(Infl_d,5)) %>%
                mutate(lag5.Infl_f = lag(Infl_f,5)) %>%
                mutate(lag5.Int_d = lag(Int_d,5)) %>%
                mutate(lag5.Int_f = lag(Int_f,5)) %>%
    
                mutate(lag6.Exchange = lag(Exchange,6)) %>%
                mutate(lag6.X1Y_Yield_d = lag(X1Y_Yield_d,6)) %>%
                mutate(lag6.X1Y_Yield_f = lag(X1Y_Yield_f,6)) %>%
                mutate(lag6.Infl_d = lag(Infl_d,6)) %>%
                mutate(lag6.Infl_f = lag(Infl_f,6)) %>%
                mutate(lag6.Int_d = lag(Int_d,6)) %>%
                mutate(lag6.Int_f = lag(Int_f,6)) %>%

                mutate(lag7.Exchange = lag(Exchange,7)) %>%
                mutate(lag7.X1Y_Yield_d = lag(X1Y_Yield_d,7)) %>%
                mutate(lag7.X1Y_Yield_f = lag(X1Y_Yield_f,7)) %>%
                mutate(lag7.Infl_d = lag(Infl_d,7)) %>%
                mutate(lag7.Infl_f = lag(Infl_f,7)) %>%
                mutate(lag7.Int_d = lag(Int_d,7)) %>%
                mutate(lag7.Int_f = lag(Int_f,7)) %>%

                mutate(lag8.Exchange = lag(Exchange,8)) %>%
                mutate(lag8.X1Y_Yield_d = lag(X1Y_Yield_d,8)) %>%
                mutate(lag8.X1Y_Yield_f = lag(X1Y_Yield_f,8)) %>%
                mutate(lag8.Infl_d = lag(Infl_d,8)) %>%
                mutate(lag8.Infl_f = lag(Infl_f,8)) %>%
                mutate(lag8.Int_d = lag(Int_d,8)) %>%
                mutate(lag8.Int_f = lag(Int_f,8))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00681947885573587"  "0.00691188993265094" 
        "Variance" "8.25743468710592e-05" "8.13808267352957e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00455615419014244" 
        "3.94297313355836e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0191725249021173"   "0.0192645404191145"  
        "Variance" "0.000127978426107884" "0.000126700807904745"
        [,4]                 
output1 "Full Forest"        
        "0.0134108666692565" 
        "6.1815314894508e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.00497110740030089"  "0.00493054924386664"
        "Variance" "2.97654049446405e-05" "3.1270931161642e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00466204917870393" 
        "2.37485404662743e-05"

[1] "japan"


[,1]       [,2]                  [,3]                 
output1 "Full"     "Full Tree"           "Full Pruned"        
        "Mean"     "0.0282567083398063"  "0.0280145588304149" 
        "Variance" "0.00015785838850127" "0.00015503882393694"
        [,4]                  
output1 "Full Forest"         
        "0.0195014561704828"  
        "6.17542423771668e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0156683942167517"   "0.0155342162891388"  
        "Variance" "0.000111413714744211" "0.000110923956441094"
        [,4]                  
output1 "Full Forest"         
        "0.00794518858211771" 
        "5.18056507136565e-05"

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00720169695201122"  "0.00717857783597736" 
        "Variance" "7.53416612549902e-05" "7.52838981229405e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00377265310081646" 
        "3.85134979758748e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0161007370279517"   "0.0158506046712425"  
        "Variance" "7.41388333842152e-05" "6.82545324257451e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.0117937102367853"  
        "6.77136418332446e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00421825470391673"  "0.00424706058672509" 
        "Variance" "3.11533130345124e-05" "3.16643413437764e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00441892712788619" 
        "1.67473017317252e-05"

[1] "japan"


[,1]       [,2]                  [,3]                  
output1 "AIC"      "AIC Tree"            "AIC Pruned"          
        "Mean"     "0.0288610001528075"  "0.0288556658898031"  
        "Variance" "0.00018559439006926" "0.000186538193993641"
        [,4]                  
output1 "AIC Forest"          
        "0.0194989468913627"  
        "4.73702379712535e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0148803495025235"   "0.0144179469880041"  
        "Variance" "9.80123783913825e-05" "0.000100931057112197"
        [,4]                  
output1 "AIC Forest"          
        "0.00902913828954807" 
        "0.000102209277399995"

In [15]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4)) %>%
    
                mutate(lag5.Exchange = lag(Exchange,5)) %>%
                mutate(lag5.X1Y_Yield_d = lag(X1Y_Yield_d,5)) %>%
                mutate(lag5.X1Y_Yield_f = lag(X1Y_Yield_f,5)) %>%
                mutate(lag5.Infl_d = lag(Infl_d,5)) %>%
                mutate(lag5.Infl_f = lag(Infl_f,5)) %>%
                mutate(lag5.Int_d = lag(Int_d,5)) %>%
                mutate(lag5.Int_f = lag(Int_f,5)) %>%
    
                mutate(lag6.Exchange = lag(Exchange,6)) %>%
                mutate(lag6.X1Y_Yield_d = lag(X1Y_Yield_d,6)) %>%
                mutate(lag6.X1Y_Yield_f = lag(X1Y_Yield_f,6)) %>%
                mutate(lag6.Infl_d = lag(Infl_d,6)) %>%
                mutate(lag6.Infl_f = lag(Infl_f,6)) %>%
                mutate(lag6.Int_d = lag(Int_d,6)) %>%
                mutate(lag6.Int_f = lag(Int_f,6)) %>%

                mutate(lag7.Exchange = lag(Exchange,7)) %>%
                mutate(lag7.X1Y_Yield_d = lag(X1Y_Yield_d,7)) %>%
                mutate(lag7.X1Y_Yield_f = lag(X1Y_Yield_f,7)) %>%
                mutate(lag7.Infl_d = lag(Infl_d,7)) %>%
                mutate(lag7.Infl_f = lag(Infl_f,7)) %>%
                mutate(lag7.Int_d = lag(Int_d,7)) %>%
                mutate(lag7.Int_f = lag(Int_f,7)) %>%

                mutate(lag8.Exchange = lag(Exchange,8)) %>%
                mutate(lag8.X1Y_Yield_d = lag(X1Y_Yield_d,8)) %>%
                mutate(lag8.X1Y_Yield_f = lag(X1Y_Yield_f,8)) %>%
                mutate(lag8.Infl_d = lag(Infl_d,8)) %>%
                mutate(lag8.Infl_f = lag(Infl_f,8)) %>%
                mutate(lag8.Int_d = lag(Int_d,8)) %>%
                mutate(lag8.Int_f = lag(Int_f,8)) %>%
    
                mutate(lag9.Exchange = lag(Exchange,9)) %>%
                mutate(lag9.X1Y_Yield_d = lag(X1Y_Yield_d,9)) %>%
                mutate(lag9.X1Y_Yield_f = lag(X1Y_Yield_f,9)) %>%
                mutate(lag9.Infl_d = lag(Infl_d,9)) %>%
                mutate(lag9.Infl_f = lag(Infl_f,9)) %>%
                mutate(lag9.Int_d = lag(Int_d,9)) %>%
                mutate(lag9.Int_f = lag(Int_f,9))

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00688464601939339"  "0.00692051215770299" 
        "Variance" "6.78283238872792e-05" "6.73627278820789e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00499734076862369" 
        "3.91746678462974e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.018559912364554"    "0.0186502027373072"  
        "Variance" "0.000155115258102305" "0.000156048693641692"
        [,4]                  
output1 "Full Forest"         
        "0.0117277801853307"  
        "5.10149439376311e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00606367614779166"  "0.00621883436343913" 
        "Variance" "3.91599716011118e-05" "3.78008425383455e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00488610732766068" 
        "2.74662030940326e-05"

[1] "japan"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0317248840187987"   "0.0311208321708939" 
        "Variance" "0.000287143385351351" "0.00028649425116522"
        [,4]                  
output1 "Full Forest"         
        "0.020056679550138"   
        "8.09523098483579e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0105298205698498"   "0.0100160168849398"  
        "Variance" "5.41771177759079e-05" "5.87770380191235e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00717086902746789" 
        "3.90992018785889e-05"

[1] "canada"


[,1]       [,2]                  [,3]                  
output1 "AIC"      "AIC Tree"            "AIC Pruned"          
        "Mean"     "0.00706065350902875" "0.00698684453435173" 
        "Variance" "6.4161027929064e-05" "6.35805338491741e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00496035156413272" 
        "4.62935334544004e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0179074713243165"   "0.0177521792987901"  
        "Variance" "0.000128415169396342" "0.000128107135895317"
        [,4]                  
output1 "AIC Forest"          
        "0.0104509873819131"  
        "3.36014524372014e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00588881746667127"  "0.00588510911453325" 
        "Variance" "3.14794576669526e-05" "2.82456954536241e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00385358320812958" 
        "1.66657651173275e-05"

[1] "japan"


[,1]       [,2]                   [,3]                
output1 "AIC"      "AIC Tree"             "AIC Pruned"        
        "Mean"     "0.0321145869754097"   "0.0319260536104283"
        "Variance" "0.000253638592693912" "0.0002472665555028"
        [,4]                  
output1 "AIC Forest"          
        "0.0184043480877135"  
        "4.32466244040458e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00825814125651387"  "0.0084239273887678"  
        "Variance" "6.80557341410091e-05" "6.60906403996776e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00947632468592924" 
        "8.65451375568666e-05"

In [16]:
countries <- c('japan','europe','korea','mexico','canada')
for (country in countries){
ex_rates <- read.csv('topfive.csv')
ex_rates <- subset(ex_rates, ex_rates$Country.y==country)
    
full <- subset(ex_rates, select = c(Pct_Chg, Exchange, X1Y_Yield_d, 
                X1Y_Yield_f, Int_d, Int_f,  Infl_d, Infl_f, GDPG_d,
                GDPG_f, BOT_f, BOT_d, FER_f))

full <- full %>% mutate(lag1.Exchange = lag(Exchange,1)) %>%
                mutate(lag1.X1Y_Yield_d = lag(X1Y_Yield_d,1)) %>%
                mutate(lag1.X1Y_Yield_f = lag(X1Y_Yield_f,1)) %>%
                mutate(lag1.Infl_d = lag(Infl_d,1)) %>%
                mutate(lag1.Infl_f = lag(Infl_f,1)) %>%
                mutate(lag1.Int_d = lag(Int_d,1)) %>%
                mutate(lag1.Int_f = lag(Int_f,1)) %>%

                mutate(lag2.Exchange = lag(Exchange,2)) %>%
                mutate(lag2.X1Y_Yield_d = lag(X1Y_Yield_d,2)) %>%
                mutate(lag2.X1Y_Yield_f = lag(X1Y_Yield_f,2)) %>%
                mutate(lag2.Infl_d = lag(Infl_d,2)) %>%
                mutate(lag2.Infl_f = lag(Infl_f,2)) %>%
                mutate(lag2.Int_d = lag(Int_d,2)) %>%
                mutate(lag2.Int_f = lag(Int_f,2)) %>%
    
                mutate(lag3.Exchange = lag(Exchange,3)) %>%
                mutate(lag3.X1Y_Yield_d = lag(X1Y_Yield_d,3)) %>%
                mutate(lag3.X1Y_Yield_f = lag(X1Y_Yield_f,3)) %>%
                mutate(lag3.Infl_d = lag(Infl_d,3)) %>%
                mutate(lag3.Infl_f = lag(Infl_f,3)) %>%
                mutate(lag3.Int_d = lag(Int_d,3)) %>%
                mutate(lag3.Int_f = lag(Int_f,3)) %>%
    
                mutate(lag4.Exchange = lag(Exchange,4)) %>%
                mutate(lag4.X1Y_Yield_d = lag(X1Y_Yield_d,4)) %>%
                mutate(lag4.X1Y_Yield_f = lag(X1Y_Yield_f,4)) %>%
                mutate(lag4.Infl_d = lag(Infl_d,4)) %>%
                mutate(lag4.Infl_f = lag(Infl_f,4)) %>%
                mutate(lag4.Int_d = lag(Int_d,4)) %>%
                mutate(lag4.Int_f = lag(Int_f,4)) %>%
    
                mutate(lag5.Exchange = lag(Exchange,5)) %>%
                mutate(lag5.X1Y_Yield_d = lag(X1Y_Yield_d,5)) %>%
                mutate(lag5.X1Y_Yield_f = lag(X1Y_Yield_f,5)) %>%
                mutate(lag5.Infl_d = lag(Infl_d,5)) %>%
                mutate(lag5.Infl_f = lag(Infl_f,5)) %>%
                mutate(lag5.Int_d = lag(Int_d,5)) %>%
                mutate(lag5.Int_f = lag(Int_f,5)) %>%
    
                mutate(lag6.Exchange = lag(Exchange,6)) %>%
                mutate(lag6.X1Y_Yield_d = lag(X1Y_Yield_d,6)) %>%
                mutate(lag6.X1Y_Yield_f = lag(X1Y_Yield_f,6)) %>%
                mutate(lag6.Infl_d = lag(Infl_d,6)) %>%
                mutate(lag6.Infl_f = lag(Infl_f,6)) %>%
                mutate(lag6.Int_d = lag(Int_d,6)) %>%
                mutate(lag6.Int_f = lag(Int_f,6)) %>%

                mutate(lag7.Exchange = lag(Exchange,7)) %>%
                mutate(lag7.X1Y_Yield_d = lag(X1Y_Yield_d,7)) %>%
                mutate(lag7.X1Y_Yield_f = lag(X1Y_Yield_f,7)) %>%
                mutate(lag7.Infl_d = lag(Infl_d,7)) %>%
                mutate(lag7.Infl_f = lag(Infl_f,7)) %>%
                mutate(lag7.Int_d = lag(Int_d,7)) %>%
                mutate(lag7.Int_f = lag(Int_f,7)) %>%

                mutate(lag8.Exchange = lag(Exchange,8)) %>%
                mutate(lag8.X1Y_Yield_d = lag(X1Y_Yield_d,8)) %>%
                mutate(lag8.X1Y_Yield_f = lag(X1Y_Yield_f,8)) %>%
                mutate(lag8.Infl_d = lag(Infl_d,8)) %>%
                mutate(lag8.Infl_f = lag(Infl_f,8)) %>%
                mutate(lag8.Int_d = lag(Int_d,8)) %>%
                mutate(lag8.Int_f = lag(Int_f,8)) %>%
    
                mutate(lag9.Exchange = lag(Exchange,9)) %>%
                mutate(lag9.X1Y_Yield_d = lag(X1Y_Yield_d,9)) %>%
                mutate(lag9.X1Y_Yield_f = lag(X1Y_Yield_f,9)) %>%
                mutate(lag9.Infl_d = lag(Infl_d,9)) %>%
                mutate(lag9.Infl_f = lag(Infl_f,9)) %>%
                mutate(lag9.Int_d = lag(Int_d,9)) %>%
                mutate(lag9.Int_f = lag(Int_f,9)) %>%
    
                mutate(lag10.Exchange = lag(Exchange,10)) %>%
                mutate(lag10.X1Y_Yield_d = lag(X1Y_Yield_d,10)) %>%
                mutate(lag10.X1Y_Yield_f = lag(X1Y_Yield_f,10)) %>%
                mutate(lag10.Infl_d = lag(Infl_d,10)) %>%
                mutate(lag10.Infl_f = lag(Infl_f,10)) %>%
                mutate(lag10.Int_d = lag(Int_d,10)) %>%
                mutate(lag10.Int_f = lag(Int_f,10)) 

full <- na.omit(full)
write.csv(full,file = paste(country,'_full.csv',sep=''))
}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)

print('canada')
test_aic_trees('canada',100)
print('europe')
test_aic_trees('europe',100)
print('mexico')
test_aic_trees('mexico',100)
print('japan')
test_aic_trees('japan',100)
print('korea')
test_aic_trees('korea',100)

[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00563409394203227"  "0.00564438212499927" 
        "Variance" "4.54186956112902e-05" "4.50671307406396e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00461066777799263" 
        "3.96442143293759e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0151217018496651"   "0.0153012434127315"  
        "Variance" "6.97866391727101e-05" "7.22146592991335e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0113965787755688"  
        "4.93611502963855e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00824862179701571"  "0.00806109380063217" 
        "Variance" "6.11513790054365e-05" "6.21862374074834e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00487092022287228" 
        "2.22563819138239e-05"

[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0289748139069343"   "0.0288063797097178"  
        "Variance" "0.000162612055288843" "0.000166971384249707"
        [,4]                  
output1 "Full Forest"         
        "0.0200058805003958"  
        "5.79248202222632e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0099565723296568"   "0.00998910684744552" 
        "Variance" "7.96342891880055e-05" "7.96611325558872e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00808917290457083" 
        "5.81346228383466e-05"

[1] "canada"


ERROR: Error in `[.data.frame`(full, var_list): undefined columns selected


[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0137429166377971"   "0.0137697506368963"  
        "Variance" "0.000116296603496673" "0.000115492520219748"
        [,4]                  
output1 "AIC Forest"          
        "0.0111586061391944"  
        "5.75885510059824e-05"

[1] "mexico"


ERROR: Error in `[.data.frame`(full, var_list): undefined columns selected


[1] "japan"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.0296440302395559"   "0.0296440172972504"  
        "Variance" "0.000174909431687258" "0.000174266383257628"
        [,4]                 
output1 "AIC Forest"         
        "0.0190270215807868" 
        "4.9186765041553e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "AIC"      "AIC Tree"             "AIC Pruned"          
        "Mean"     "0.00958579691676819"  "0.00960645211932238" 
        "Variance" "9.81619074671622e-05" "9.77585523131729e-05"
        [,4]                  
output1 "AIC Forest"          
        "0.00775683615187804" 
        "5.64308796330171e-05"