In [1]:
setwd('C:/Users/Eddie/Documents/GitHub/ML-Ex-Rates/Results')
library(rpart)
library(randomForest)
library(dplyr)

setwd('C:/Users/Eddie/Documents/GitHub/ML-Ex-Rates/Results')
library(rpart)
library(randomForest)
library(dplyr)

test_full_trees <- function(country, B){
    full <- read.csv(paste(country,'_final.csv',sep=''))
    full <- full[,-1]
    rownames(full) <- 1:nrow(full)
    
    # Split into testing and training
    n <- dim(full)[1]
    n1 <- round(n/5)
    
    # full Tree Models
    set.seed(19890211)
    fulltree.TE_list <- vector(length=0)
    for(i in 1:B){
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        fulltree.test <- predict(treemodel,test[,-1])
        fulltree.TE <- mean((test[,1]-fulltree.test)^2)
        fulltree.TE_list <- c(fulltree.TE_list, fulltree.TE)
    }
    
    # pruned tree models
    set.seed(19890211)
    fullpruned.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        prunedtree <- prune(treemodel,
                    treemodel$cptable[which.min(treemodel$cptable[,'xerror']),"CP"])
        fullpruned.test <- predict(prunedtree,test[,-1])
        fullpruned.TE <- mean((test[,1]-fullpruned.test)^2)
        fullpruned.TE_list <- c(fullpruned.TE_list,fullpruned.TE)  
    }
    
    # Full Random Forest
    set.seed(19890211)
    fullforest.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        forestmodel <- randomForest(Pct_Chg ~ ., data = train)
        fullforest.test <- predict(forestmodel,test[,-1])
        fullforest.TE <- mean((test[,1]-fullforest.test)^2)
        fullforest.TE_list <- c(fullforest.TE_list, fullforest.TE) 
        
    }

output1 <- c('Full','Full Tree','Full Pruned', 'Full Forest')
output1 <- rbind(output1,c('Mean',mean(fulltree.TE_list),mean(fullpruned.TE_list),mean(fullforest.TE_list)))
output1 <- rbind(output1,c('Variance',var(fulltree.TE_list),var(fullpruned.TE_list),var(fullforest.TE_list)))


return(output1)

}

print('canada')
test_full_trees('canada',100)
print('europe')
test_full_trees('europe',100)
print('mexico')
test_full_trees('mexico',100)
print('japan')
test_full_trees('japan',100)
print('korea')
test_full_trees('korea',100)


randomForest 4.6-10
Type rfNews() to see new features/changes/bug fixes.

Attaching package: 'dplyr'

The following object is masked from 'package:randomForest':

    combine

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00738881355527953"  "0.00734461551975625" 
        "Variance" "6.81083472834278e-05" "6.63864784116058e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00449553836717566" 
        "3.53430112402808e-05"

[1] "europe"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.018559912364554"    "0.0186502027373072"  
        "Variance" "0.000155115258102305" "0.000156048693641692"
        [,4]                  
output1 "Full Forest"         
        "0.0117277801853307"  
        "5.10149439376311e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00707414274690525"  "0.00706475831543387" 
        "Variance" "3.20399959092261e-05" "3.13438412036878e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00376004145962435" 
        "1.19293745642211e-05"

[1] "japan"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0317248840187987"   "0.0311208321708939" 
        "Variance" "0.000287143385351351" "0.00028649425116522"
        [,4]                  
output1 "Full Forest"         
        "0.020056679550138"   
        "8.09523098483579e-05"

[1] "korea"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0105298205698498"   "0.0100160168849398"  
        "Variance" "5.41771177759079e-05" "5.87770380191235e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00717086902746789" 
        "3.90992018785889e-05"