In [1]:
setwd('C:/Users/Eddie/Documents/GitHub/ML-Ex-Rates/Results')
library(rpart)
library(randomForest)

test_full_trees <- function(country, B){
    full <- read.csv(paste(country,'_full.csv',sep=''))
    full <- full[,-1]
    rownames(full) <- 1:nrow(full)
    
    # Split into testing and training
    n <- dim(full)[1]
    n1 <- round(n/5)
    
    # full Tree Models
    set.seed(19890211)
    fulltree.TE_list <- vector(length=0)
    for(i in 1:B){
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        fulltree.test <- predict(treemodel,test[,-1])
        fulltree.TE <- mean((test[,1]-fulltree.test)^2)
        fulltree.TE_list <- c(fulltree.TE_list, fulltree.TE)
    }
    
    # pruned tree models
    set.seed(19890211)
    fullpruned.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        treemodel <- rpart(Pct_Chg ~ ., method="anova",data = train)
        prunedtree <- prune(treemodel,
                    treemodel$cptable[which.min(treemodel$cptable[,'xerror']),"CP"])
        fullpruned.test <- predict(prunedtree,test[,-1])
        fullpruned.TE <- mean((test[,1]-fullpruned.test)^2)
        fullpruned.TE_list <- c(fullpruned.TE_list,fullpruned.TE)  
    }
    
    # Full Random Forest
    set.seed(19890211)
    fullforest.TE_list <- vector(length=0)
    for(i in 1:B) {
        start <- sample(1:(n-n1-1),1)
        flag <- (start+6):(start+n1-6)
        train <- full[-flag,]
        test <- full[flag,]
        
        forestmodel <- randomForest(Pct_Chg ~ ., data = train)
        fullforest.test <- predict(forestmodel,test[,-1])
        fullforest.TE <- mean((test[,1]-fullforest.test)^2)
        fullforest.TE_list <- c(fullforest.TE_list, fullforest.TE) 
        
    }

output1 <- c('Full','Full Tree','Full Pruned', 'Full Forest')
output1 <- rbind(output1,c('Mean',mean(fulltree.TE_list),mean(fullpruned.TE_list),mean(fullforest.TE_list)))
output1 <- rbind(output1,c('Variance',var(fulltree.TE_list),var(fullpruned.TE_list),var(fullforest.TE_list)))


return(output1)

}

print('canada')
test_full_trees('canada',10)
print('europe')
test_full_trees('europe',10)
print('mexico')
test_full_trees('mexico',10)
print('japan')
test_full_trees('japan',10)
print('korea')
test_full_trees('korea',10)

randomForest 4.6-10
Type rfNews() to see new features/changes/bug fixes.


[1] "canada"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.00286186754928327"  "0.00272616818424158" 
        "Variance" "9.73573559258191e-06" "1.00597794608522e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00371842861805248" 
        "2.89904602671658e-05"

[1] "europe"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0141188413996312"   "0.0145516771244521" 
        "Variance" "2.14367588826176e-05" "3.0844576614562e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00887244130575673" 
        "2.27384581385476e-05"

[1] "mexico"


[,1]       [,2]                   [,3]                  
output1 "Full"     "Full Tree"            "Full Pruned"         
        "Mean"     "0.0077701432084026"   "0.00762001524070815" 
        "Variance" "6.87165671409264e-05" "7.24558380221787e-05"
        [,4]                  
output1 "Full Forest"         
        "0.00513111309502257" 
        "2.51513461688025e-05"

[1] "japan"


[,1]       [,2]                  [,3]                  
output1 "Full"     "Full Tree"           "Full Pruned"         
        "Mean"     "0.030954847425092"   "0.0320798515009658"  
        "Variance" "0.00015674290687077" "0.000166866566216661"
        [,4]                  
output1 "Full Forest"         
        "0.0172915545739086"  
        "5.54138475996108e-05"

[1] "korea"


[,1]       [,2]                   [,3]                 
output1 "Full"     "Full Tree"            "Full Pruned"        
        "Mean"     "0.0107077822435343"   "0.0104522252175932" 
        "Variance" "8.12971069771746e-05" "8.1545096726855e-05"
        [,4]                  
output1 "Full Forest"         
        "0.0115367621337741"  
        "0.000113930868570151"